#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cupid_cmd() {
  declare desc="dokku memory stats plugin"
  local cmd=""
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  docker stats --no-stream $(sudo docker ps -q | xargs -L1 sudo docker inspect | jq ".[0].Name" | sed 's/"//g' | sed 's/\///') | sort -nr -k 3
}

cupid_cmd "$@"
