#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cupid_cmd() {
  declare desc="prints Hello World"
  local cmd="hello:world"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  cat << EOH
　　　　 ノヽ
　　　 ／ヾツ＼
　　 ／　 )ﾉ　 ＼
　　/　　　　　　ﾍ
　 ｜　＿　　＿　｜
　 <ﾍ　,,,　 ,,, />
　　Y (●)　(●) Y
　　ヽ ⌒)ー(⌒ ノ
　　　＞―――＜
　 _／　　　　　＼_
　(ﾐ　/　　　　Ｙ ﾐ)
　 ￣｜　　　　｜￣
　　 (＼　＾　／)
　　 ヽ ＼＿／ /
　　　ヽ　｜　/
　　　 (mn人nm)

♪　キュ〜ピ〜三分クッキングの時間です　♪
https://www.youtube.com/watch?v=cy3eznufCKE
EOH
}

cupid_cmd "$@"
